[package]
name = "decimal-macros"
version = "0.1.0"
authors = ["Callum Tolley <cgtrolley@gmail.com>"]

[lib]
name = "decimal_macros"
plugin = true

[dependencies]
decimal = { path = "../" }
libc = "~0.2"

[build-dependencies]
gcc = "~0.3"
