[package]
name = "decimal-macros"
version = "0.2.0"
authors = ["Callum Tolley <cgtrolley@gmail.com>"]

[lib]
name = "decimal_macros"
proc-macro = true

[dependencies]
decimal = { path = "../" }
libc = "~0.2"
quote = "0.6"
proc-macro2 = "0.4"

[build-dependencies]
gcc = "0.3"

[workspace]
